### PR TITLE
Basic union support

### PR DESCRIPTION
**Pull request by willtonkin**
added basic union support.

Noteworthy stuff:

- changed `oneOf` to `anyOf` for validity against outputted schemas ([ref](https://json-schema.org/understanding-json-schema/reference/combining.html))
- as with #2 I had to update snapshots, unsure why there's a mismatch

### CODE REVIEW

**Comment by willtonkin** [comment]
merge conflicts resolved 👍

**Comment by willtonkin** [comment]
@transitive-bullshit Updated snapshots

**Comment by transitive-bullshit** [comment]
Oooooooooh that's a beautiful PR right there 😉 Thanks, Will!

**Comment by transitive-bullshit** [comment]
Latest released as `v1.0.3`.

**Comment by willtonkin** [comment]
Lovely, thanks @transitive-bullshit 🙏

**Pull request merged**
